name: track_run
description: Um app de corrida territorial no Brasil.
publish_to: 'none' # app local

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  h3_flutter: ^0.6.6
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
